steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/worker-api:0.1",
        "-f",
        "src_worker/Dockerfile",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/worker-api:0.1"
