version: "3.8"

services:
  worker:
    build:
      context: ..
      dockerfile: ./docker-celery-bucket/Dockerfile
    env_file:
      - ./.env
    command: ["celery", "-A", "tasks", "worker", "-l", "info"]
