version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: ./docker-web/Dockerfile
    env_file:
      - ./.env
    volumes:
      - /mnt/nfs_videos:/app/static/uploads
    ports:
      - "80:5000"
